### ISSUE TITLE
x_maintenance : [IMP] add Air-condition Mantenance menu

### ISSUE THREAD

**Issue by kitcharoenp** [kitcharoenp/x_odoo_10_addons#5]
- List view : แสดงเฉพาะ รายการบำรุงรักษาแอร์
- Form view :  เลือก equipment ได้เฉพาะแอร์

**Comment by oragarn** [comment]
- รอบการล้างแอร์

**Comment by oragarn** [comment]
- สามารถบอกรายละเอียดงานซ่อมได้

**Comment by kitcharoenp** [comment]
แยกออกมาต่างหากแล้วในดมดูลชือ x_air_conditioner
